# Trigger on commits to the master branch, but only if the changes
# were in a location that affects the NuGet package.
trigger:
  branches:
    include:
    - master
  paths:
    include:
    - Source/Mono.Cecil
    - Source/MSBuildTools.Unity.Nuget

# Do not trigger for PRGate builds
pr: none

pool:
  vmImage: 'windows-latest'

workspace:
 clean: all

steps:
- template: Templates/CommonInitialization.yml
- template: Templates/BuildMSBuildForUnityNuget.yml
# Commenting out the ability to publish the NuGet packages until we get approval from legal
#- template: Templates/PublishArtifacts.yml
- template: Templates/PublishNuGetPackages.yml