# Trigger on commits to the master branch, but only if the changes
# were in a location that affects the NuGet package.
trigger:
  branches:
    include:
    - master
  paths:
    include:
    - Source/Mono.Cecil
    - Source/MSBuildTools.Unity.Nuget

# Do not trigger for PRGate builds
pr: none

pool:
  vmImage: 'windows-latest'

workspace:
 clean: all

steps:
- template: Templates/CommonInitialization.yml
- template: Templates/BuildMSBuildForUnityNuget.yml
- task: EsrpCodeSigning@1
  inputs:
    ConnectedServiceName: 'ESRP Code Signing'
    FolderPath: '$(System.DefaultWorkingDirectory)\Source\MSBuildTools.Unity.Nuget\bin\Release'
    Pattern: 'MSBuildForUnity.*.nupkg'
    signConfigType: 'inlineSignParams'
    inlineOperation: |
      [
        {
          "KeyCode" : "CP-401405",
          "OperationCode" : "NuGetSign",
          "Parameters" : {},
          "ToolName" : "sign",
          "ToolVersion" : "1.0"
        },
        {
          "KeyCode" : "CP-401405",
          "OperationCode" : "NuGetVerify",
          "Parameters" : {},
          "ToolName" : "sign",
          "ToolVersion" : "1.0"
        }
      ]
- template: Templates/PublishArtifacts.yml
#- template: Templates/PublishNuGetPackages.yml