# Trigger on commits to the master branch, but only if the changes
# were in a location that affects the NuGet package.
trigger:
  branches:
    include:
    - master
  paths:
    include:
    - Source/Mono.Cecil
    - Source/MSBuildTools.Unity.Nuget

# Do not trigger for PRGate builds
pr: none

pool:
  vmImage: 'windows-latest'

workspace:
 clean: all

steps:
- template: Templates/CommonInitialization.yml
- template: Templates/BuildMSBuildForUnityNuGetBinaries.yml
- template: Templates/SignBinaries.yml
- template: Templates/BuildMSBuildForUnityNuGetPackage.yml
- template: Templates/SignNuGetPackages.yml
- template: Templates/PublishArtifacts.yml
- task: ComponentGovernanceComponentDetection@0
  displayName: "Scan Third Party Components"
  inputs:
    scanType: 'Register'
    verbosity: 'Verbose'
    alertWarningLevel: 'High'
    failOnAlert: true
- template: Templates/PublishNuGetPackages.yml