# Trigger on commits to the master branch, but only if the changes
# were in a location that affects the UPM package.
trigger:
  branches:
    include:
    - master
  paths:
    include:
    - Source/MSBuildTools.Unity/Packages

pr: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Npm@1
# Only update the version on master branch
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master') 
  inputs:
    command: 'custom'
    customCommand: --no-git-tag-version version prerelease --preid=$(Build.BuildNumber)
    workingDir: 'Source/MSBuildTools.Unity/Packages/com.microsoft.msbuildforunity'
  displayName: 'Update UPM Version'
  
- task: Npm@1
  inputs:
    command: 'publish'
    workingDir: 'Source/MSBuildTools.Unity/Packages/com.microsoft.msbuildforunity'
    publishRegistry: 'useFeed'
    publishFeed: '0cb95e25-9194-4ccd-9afb-439b25ecb93a/a3d1c3cc-6042-4e05-b699-39a947e75639'